@startuml administrador

actor administrador

' CRUD funcionario
administrador --> (cadastrar funcionario) #Red
administrador --> (atualizar funcionario) #Red
administrador --> (excluir funcionario) #Red
administrador --> (consultar funcionario) #Red

@enduml